### PR TITLE
Add code style project settings. #345

### PR DESCRIPTION
**Pull request by lemonboston**

### CODE REVIEW

**Comment by lemonboston** [comment]
Note: code style xml is from ED-SDK

**Comment by lemonboston** [comment]
Added `.editorconfig` file as well (exported from IntelliJ Idea).

**Comment by dmfs** [comment]
hmm... code formatting results in different results with EditorConfig enabled. It's mostly "continuation indents" which are different (4 vs. 8).
For now I'd prefer to remove the EditorConfig file.

**Comment by lemonboston** [comment]
Removed `.editorconfig` and rebased on `staging`.

**Pull request merged**
