### PR TITLE
clarify intent label ("Add task")

### PR DESCRIPTION
**Pull request by katrinleinweber**
activity_add_task_title ("Create") left this clarification up to the icon

### CODE REVIEW

**Comment by katrinleinweber** [comment]
A more extensive solution would be https://github.com/katrinleinweber/opentasks/commit/073c4dd9ba7a642e6eb6e8ecbdb1abb6c26be68e. Please let me know if that one should be in this PR instead of the above quick fix.

**Comment by dmfs** [comment]
The "share as task" intent filter looks good. I'd prefer this one over the "quick fix. Thanks.

**Comment by katrinleinweber** [comment]
OK, here you are :-)

**Comment by dmfs** [comment]
Thanks. Looks almost good, except for the French and Brazilian translations being empty.

**Comment by katrinleinweber** [comment]
Note to self: triple–check next time m-)
Just out of curiosity about Git(Hub) itself: Would it have been a problem for the PR if I had amended & force-pushed your suggested changes into the original commit?

**Comment by dmfs** [comment]
I would expect that GitHub can handle the amended commit. I've never tried that though.

**Comment by mkroehnert** [comment]
@katrinleinweber @dmfs pull requests are associated with a repository and a branch name.
You can push additional commits or do rebased or amended force pushes as long as the branch name stays the same.
Also see the following link: https://github.com/github/hub/issues/198

**Comment by dmfs** [comment]
@mkroehnert Thanks for clarifying.

**Pull request merged**
