### PR TITLE
Update gradle and buildTools to latest. Suppress a new Lint error. #472

### PR DESCRIPTION
**Pull request by lemonboston**
This updates gradle to latest. I've also added `google()` repository and a 'clean' task in the root gradle file which is added for some reason in new projects.

Lint marked this as error afterwards:
image

I suppressed it because I don't know what is expected there. @dmfs could you please check that? Can that binary flag operation be simplified or expressed differently?

### CODE REVIEW

**Comment by dmfs** [comment]
The update caused a problem with CI: 
```
Checking the license for package Android SDK Build-Tools 26.0.2 in /usr/local/android-sdk/licenses

Warning: License for package Android SDK Build-Tools 26.0.2 not accepted.
```
Please make sure to update .travis.yml as well.

**Comment by dmfs** [comment]
Regarding the Lint warning: Apparently Lint can't handle bit arithmetic. Otherwise it would know that this operations "unsets" the given flag.
You can ignore the warning. We'll probably replace this code eventually with something cleaner.

**Comment by lemonboston** [comment]
I've updated the build tools version in `travis.yml` so the `push` build now pass but the `pr` one fails with:
```
:opentasks:connectedDebugAndroidTest
Skipping device 'test(AVD)' for 'opentasks:': Unknown API Level
 > : No compatible devices connected.[TestRunner] FAILED 
Found 1 connected device(s), 0 of which were compatible.
:opentasks:connectedDebugAndroidTest FAILED
```
Do you happen to know what this is? I see some configuration for an emulator in the yml, the version looks correct.

**Comment by dmfs** [comment]
Not sure. Have you tried adding?
```
   - android-26
```

**Comment by lemonboston** [comment]
One of the build still fails but due to https://github.com/dmfs/opentasks/issues/486
Otherwise this is ready for checking again.

**Pull request merged**
