### PR TITLE
Update portuguese translation

### PR DESCRIPTION
**Pull request by YSmhXQDd6Z**

### CODE REVIEW

**Comment by dmfs** [comment]
@lemonboston please help to review

**Comment by lemonboston** [comment]
Something is strange here, the `values-pt-rPT/strings.xml` file I see in our master is different from the one this change is originating from. There is also conflict in the file according to github here. @YSmhXQDd6Z Could you please rebase on this repository's `master`?

Or if that's problematic, you can also provide the `strings.xml` file as an attachment of a new issue here, we can commit it.

**Comment by YSmhXQDd6Z** [comment]
I updated the file there was some new strings missing

**Comment by lemonboston** [comment]
Github says here that there are unresolved conflicts in the file, @YSmhXQDd6Z could you please resolve them?

**Comment by YSmhXQDd6Z** [comment]
I noticed that but I can't resolve them with the web editor as it says "the conflicts are too complex". Can you please update the file directly using my last commit?

**Comment by dmfs** [comment]
@lemonboston please copy the file from @YSmhXQDd6Z's branch, fix the conflicts and submit a new PR.

**Comment by dmfs** [comment]
this will be handled by #429

**Pull request closed without merging**
