### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by tacsipacsi**
Translated in Hungarian. First version, I hope somebody reports my
errors. :-)

### CODE REVIEW

**Comment by dmfs** [comment]
@lemonboston please review

**Comment by lemonboston** [comment]
Hi @tacsipacsi , illetve szia! :)

I went through the translations, I think they are really good and appropriate as much as I can tell. I only found these ones missed out:
```
<!-- Priority labels -->
<string name="priority_undefined">none</string>
<string name="priority_low">low</string>
<string name="priority_medium">medium</string>
<string name="priority_high">high</string>
<string name="priority_urgent">urgent</string>
```
And 2 typos here:
```
<string name="dashclock_display_type_due">esedákes feladatok</string>
<string name="dashclock_display_type_start_and_due">kezdődő és esedákes feladatok</string>
```
And I am not sure how it is grammatically correct but maybe writing these words separated (különírva):
`Listabeállítások `and `feladatesemények`?

**Comment by tacsipacsi** [comment]
I corrected the typos and untranslated strings, thank you for finding them! The last two words are correct in this form – the second is actually "events _of_ tasks" in English. My version compresses it by leaving the equivalent of _of,_ but in this case it should be written in one word.

**Comment by lemonboston** [comment]
Thanks @tacsipacsi

@dmfs, this is ready for merge.

**Comment by dmfs** [comment]
thx, merged it into staging.

**Comment by lemonboston** [comment]
Hmm, I don't see the merge and the Hungarian file on staging, @dmfs could you please check whether you have pushed?

**Pull request closed without merging**
