### PR TITLE
Add spotless Gradle plugin

### PR DESCRIPTION
**Pull request by saschpe**
Reduces pull-request bikeshedding by applying consistent code style to
various files. The supplied configuration supports Markdown and Java.
Other languages (such as Kotlin and Groovy) are supported as well.
Include resulting code corrections.

See: https://github.com/diffplug/spotless/tree/master/plugin-gradle

### CODE REVIEW

**Comment by saschpe** [comment]
Ping

**Comment by dmfs** [comment]
@lemonboston please review

**Comment by lemonboston** [comment]
@saschpe If I add the license header config on your branch like this:

```groovy
apply plugin: 'com.diffplug.gradle.spotless'
spotless {
    freshmark {
    }
    java {
        target '**/*.java'
        trimTrailingWhitespace()
        removeUnusedImports()
        licenseHeaderFile 'APACHE-2.0.txt'
    }
}
```
and then run the `spotlessCheck` task, it fails with this (just the beginning of the error message):
```
> Task :spotlessJava
Step 'removeUnusedImports' found problem in 'opentasks-provider/src/test/java/org/dmfs/provider/tasks/model/adapters/DateTimeIterableFieldAdapterTest.java':
null
java.lang.reflect.InvocationTargetException
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$createRemoveUnusedImportsOnly$1(GoogleJavaFormatStep.java:116)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)

```
Do you by any chance know why is that?
I am trying to assess the stability and the usefulness of this tool for this project.

Note that currently it is very unlikely that anybody uses an IDE other than Android Studio (or IntelliJ Idea) for Android development and the formatting rules used by them are under version control already.
I also see that IntelliJ is not listed as an IDE whose formatter settings are supported:
https://github.com/diffplug/spotless/tree/master/plugin-gradle
So I wonder what happens if the IDE has conflicting rules with spotless, or how much value spotless can add considering the maintenance of formatting rules at 2 places.

**Comment by saschpe** [comment]
We've been using it in a couple projects without churn. The ktlint plugin had some controversies though

**Pull request closed without merging**
