### PR TITLE
Added Slovak localization file

### PR DESCRIPTION
**Pull request by ethael**
I was not able to find a language switcher, so I didn't add Slovak option there. But localization file is complete. Translation is based on Czech localization file.

### CODE REVIEW

**Comment by dmfs** [comment]
@lemonboston please help to review

**Comment by dmfs** [comment]
@ethael thanks! There is no language switcher, the language is selected automatically by Android based on the locale setting of your device. Providing a localized strings file is sufficient.

**Comment by ethael** [comment]
you're welcome. ok then! hope review will end up fine. If there will be any problem I'll be checking this thread.

**Comment by lemonboston** [comment]
I checked if all strings are translated and there is only one missing that we added recently:

```
<string name="opentasks_details_no_task_selected">No task selected</string>
```
This is displayed on tablet two pane mode when no task is selected from the list on the left, to display on the right.
@ethael If you could add this as well, the translation would be complete.

---

There is also a small new feature that we are working on with some new strings, it's not important, but if you want to translate them here, just in a comment, I'll make sure to add them.
There will be a menu item to share the task info summary:
```
    <string name="opentasks_task_details_menu_send_short">Send</string>
    <string name="opentasks_task_details_menu_send">Send to</string>
```
And this will be the template, the parts between double asterisks (**) would need the translation:

```
 <task title>
 ============

 <task description>
 [X] checked list item
 [ ] unchecked list item

 **Location**: <location>
 **Start**: <start date time> <timezone>
 **Due**: <due date time> <timezone>
 **Completed**: <due date time> <timezone>
 **Priority**: <priority text>
 **Privacy**: <privacy text>
  **Status**: <status text>
 <url>

 --
  **Shared by OpenTasks**
```

**Comment by ethael** [comment]
```
<string name="opentasks_task_details_menu_send_short">Odoslať</string>
<string name="opentasks_task_details_menu_send">Odoslať do</string>
```

```
 <task title>
 ============

 <task description>
 [X] checked list item
 [ ] unchecked list item

 **Location**: <location>
 **Začiatok**: <start date time> <timezone>
 **Koniec**: <due date time> <timezone>
 **Ukončené**: <due date time> <timezone>
 **Priorita**: <priority text>
 **Súkromné**: <privacy text>
  **Stav**: <status text>
 <url>

 --
  **Zdieľané cez OpenTasks**
```

**Comment by ethael** [comment]
@dmfs @lemonboston all done guys

**Comment by ethael** [comment]
Glad to help at least a bit. Keep it up guys!

**Pull request merged**
