### PR TITLE
Include opentasks-provider as a module into Opentasks

### PR DESCRIPTION
**Pull request by dmfs**
This integrates the latest version of Opentasks-Provider as a module into OpenTasks.
In addition it updates Gradle to version 3.3.

### CODE REVIEW

**Comment by dmfs** [comment]
@lemonboston please review.

**Comment by dmfs** [comment]
Good point. I missed that part. Will fix it.

**Comment by dmfs** [comment]
@lemonboston please check again. I've moved all the resources that belong to the provider into the provider module.

**Comment by lemonboston** [comment]
Checked, I see that `compileSdkVersion` is 23 for the app and 25 for the lib.
Don't you want to use variables for these? Like:

```
in the root project's build.gradle:
ext {
  compileSdkVersion = 19
  buildToolsVersion = "19.0.1"
}

in all the android modules:

android {
  compileSdkVersion rootProject.ext.compileSdkVersion
  buildToolsVersion rootProject.ext.buildToolsVersion
}
```
[Controlling Android properties of all your modules from the main project](http://tools.android.com/tech-docs/new-build-system/tips#TOC-Controlling-Android-properties-of-all-your-modules-from-the-main-project)
(+ minSdkVersion, targetSdkVersion, supportLibVersion)

**Comment by dmfs** [comment]
Rebased on staging and squashed commits.
@lemonboston please check again. I've taken a slightly different approach to keep all version numbers in one place.

**Pull request merged**
