### PR TITLE
Open task after saved with editor. #254

### PR DESCRIPTION
**Pull request by lemonboston**
Note: the whole method appears as change in the diff because of whitespace changes.
(I am not sure at the moment how to handle the code styles in this project..)

### CODE REVIEW

**Comment by dmfs** [comment]
@lemonboston did you test this on tablets?

**Comment by lemonboston** [comment]
Yes, I checked it, it doesn't work correctly but it doesn't work correctly in current version either, not the newly created task is selected after coming back to the 2 pane screen.
There are two updates run for selecting the item, one triggered by save and one starting from onResume() and this 2nd one selects the wrong task.
I think we could create a separate bug for this.

**Comment by dmfs** [comment]
@lemonboston please rebase and resolve conflicts

**Comment by lemonboston** [comment]
Rebased and conflicts resolved.

**Pull request merged**
