### PR TITLE
PR for #172 share task merge

### LINKED ISSUE #172: Provide sharing to Android Feature
Add Feature to share tasks with other Android apps (i. e. Email, Threema,  ES File Manager)

### PR DESCRIPTION
**Pull request by lemonboston**
fixes #172 

@dmfs please review

I've realized that the words "Share" and "Send" are both commonly used for this feature. Should we change texts to "Send", "Send task", "Sent by OpenTasks"?
I've used this _send_ versions in the Hungarian translation, it felt a little bit better, but I am not sure.

TODO German translations

### CODE REVIEW

**Comment by dmfs** [comment]
Using "Send to" sounds reasonable, but the bottom line should be "Shared by OpenTasks" not "Sent by OpenTasks".

**Comment by lemonboston** [comment]
Updated the texts.
Also noticed that location was missing from the shared text, so I added it.

**Comment by dmfs** [comment]
@lemonboston please rebase and resolve conflicts

**Comment by dmfs** [comment]
and squash

**Pull request closed without merging**
