### PR TITLE
Add QuickSettingsTile for easy task creation

### PR DESCRIPTION
**Pull request by bephinix**
This MR adds a simple QuickSettingsTile for OpenTasks, so you are able to create a task from your quick settings on the fly.

### CODE REVIEW

**Comment by wevcode** [comment]
@dmfs What do you think about it?

**Comment by dmfs** [comment]
I don't have any experience with these quick setting tiles on Android N yet. The idea sounds great. I'll check it out.

**Comment by wevcode** [comment]
@dmfs It is basically only a shortcut to a new task.

**Comment by thomas-mc-work** [comment]
Would it then be possible to add this as a widget on the home screen? That'd be great!

**Pull request merged**
